#!/bin/bash

MOPSADIR="$(cd "$(dirname "$0")" && pwd -P)/../.."

juliet=$1/C/testcases

# cwes="\
#    CWE121_Stack_Based_Buffer_Overflow \
#    CWE122_Heap_Based_Buffer_Overflow \
#    CWE123_Write_What_Where_Condition \
#    CWE124_Buffer_Underwrite \
#    CWE126_Buffer_Overread \
#    CWE127_Buffer_Underread \
#    CWE190_Integer_Overflow \
#    CWE191_Integer_Underflow \
#    CWE369_Divide_by_Zero \
#    CWE457_Use_of_Uninitialized_Variable \
#    CWE476_NULL_Pointer_Dereference \
#    CWE562_Return_of_Stack_Variable_Address"

# CWE476_NULL_Pointer_Dereference \
cwes="CWE190_Integer_Overflow"
subdirs="s01 s02 s03 s04 s05 s06 s07"

echo "["
for cwe in ${cwes}; do
    for subd in ${subdirs}; do
        directory=${juliet}/${cwe}/${subd}
        cases=$(find ${directory} -regextype posix-egrep -regex ".*[0-9]a?\.c" | sed "s/a\.c/\.c/" | sed "s/\.c//" | sort)
        for c in ${cases}; do
            ${MOPSADIR}/scripts/juliet/mopsa-juliet-case-bench ${c}
        done

    done
done
echo "]"
