#!/bin/bash

MOPSADIR="$(cd "$(dirname "$0")" && pwd -P)/../.."

directory=$(dirname $1)
casename=$(basename $1 .c)

files=$(find ${directory} -name "${casename}*.c" | sort -nr)
good="${casename}_good"
bad="${casename}_bad"

echo "Analyzing ${casename}"
echo "Good case"
${MOPSADIR}/scripts/mopsa-c -cell-max-expand=20 -stub ${MOPSADIR}/analyzer/stubs/c/juliet -c-function "${good}" ${MOPSADIR}/analyzer/stubs/c/juliet/std_testcase.c ${MOPSADIR}/analyzer/stubs/c/juliet/std_testcase_io.c ${files}
echo "Bad case"
${MOPSADIR}/scripts/mopsa-c -cell-max-expand=20 -stub ${MOPSADIR}/analyzer/stubs/c/juliet -c-function "${bad}" ${MOPSADIR}/analyzer/stubs/c/juliet/std_testcase.c ${MOPSADIR}/analyzer/stubs/c/juliet/std_testcase_io.c ${files}
echo
echo "===================================================="
echo
