variables:
  MOPSA_C: "./bin/mopsa -lang=c -config=./analyzer/configs/c.json -stub=./analyzer/stubs/c -unittest"
  MOPSA_U: "./bin/mopsa -lang=universal -config=./analyzer/configs/default.universal.json"
  MOPSA_PY: "./bin/mopsa -lang=python -config=./analyzer/configs/py.json -stub=./analyzer/stubs/python -unittest"

image: mopsa-build

stages:
- build
- test

build_job:
  stage: build
  script:
    - eval `opam config env`
    - make -j
  artifacts:
    paths:
    - ./bin/mopsa
    - ./analyzer/_build/mopsa.native
    expire_in: 2h

.test-c:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_C analyzer/tests/c/$C_FILE

.test-u:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_C analyzer/tests/universal/$U_FILE

.test-py:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_PY analyzer/tests/universal/$PY_FILE

test-c 1/12:
  variables:
    C_FILE: 'array_tests.c'
  extends: .test-c

test-c 2/12:
  variables:
    C_FILE: 'enum_tests.c'
  extends: .test-c

test-c 3/12:
  variables:
    C_FILE: 'for_tests.c'
  extends: .test-c

test-c 4/12:
  variables:
    C_FILE: 'function_tests.c'
  extends: .test-c

test-c 5/12:
  variables:
    C_FILE: 'goto_tests.c'
  extends: .test-c

test-c 6/12:
  variables:
    C_FILE: 'int_tests.c'
  extends: .test-c

test-c 7/12:
  variables:
    C_FILE: 'malloc_tests.c'
  extends: .test-c

test-c 8/12:
  variables:
    C_FILE: 'pointer_tests.c'
  extends: .test-c

test-c 9/12:
  variables:
    C_FILE: 'string_tests.c'
  extends: .test-c

test-c 10/12:
  variables:
    C_FILE: 'struct_tests.c'
  extends: .test-c

test-c 11/12:
  variables:
    C_FILE: 'switch_tests.c'
  extends: .test-c

test-c 12/12:
  variables:
    C_FILE: 'union_tests.c'
  extends: .test-c

test-u 1/1:
  variables:
    U_FILE: 'int_tests.u'
  extends: .test-u


test-py 1/15:
  variables:
    PY_FILE: 'bool_tests.py'
  extends: .test-py

test-py 2/15:
  variables:
    PY_FILE: 'builtins_tests.py'
  extends: .test-py

test-py 3/15:
  variables:
    PY_FILE: 'class_tests.py'
  extends: .test-py

test-py 4/15:
  variables:
    PY_FILE: 'dict_tests.py'
  extends: .test-py

test-py 5/15:
  variables:
    PY_FILE: 'exception_tests.py'
  extends: .test-py

test-py 6/15:
  variables:
    PY_FILE: 'float_tests.py'
  extends: .test-py

test-py 7/15:
  variables:
    PY_FILE: 'function_tests.py'
  extends: .test-py

test-py 8/15:
  variables:
    PY_FILE: 'generator_tests.py'
  extends: .test-py

test-py 9/15:
  variables:
    PY_FILE: 'int_tests.py'
  extends: .test-py

test-py 10/15:
  variables:
    PY_FILE: 'iter_assign_tests.py'
  extends: .test-py

test-py 11/15:
  variables:
    PY_FILE: 'list_tests.py'
  extends: .test-py

test-py 12/15:
  variables:
    PY_FILE: 'loop_tests.py'
  extends: .test-py

test-py 13/15:
  variables:
    PY_FILE: 'operator_tests.py'
  extends: .test-py

test-py 14/15:
  variables:
    PY_FILE: 'str_tests.py'
  extends: .test-py

test-py 15/15:
  variables:
    PY_FILE: 'with_tests.py'
  extends: .test-py
