variables:
  MOPSA_C: "./bin/mopsa-c -unittest"
  MOPSA_U: "./bin/mopsa-universal -unittest"
  MOPSA_PY: "./bin/mopsa-python -unittest"
  MOPSA_PYTY: "./bin/mopsa-python-types -unittest -debug=unittest"
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

image: mopsa-build

stages:
- build
- test
- benchmarks

build_job:
  stage: build
  script:
    - eval `opam config env`
    - make -j
  artifacts:
    paths:
    - ./bin/mopsa
    - ./analyzer/_build/mopsa.native
    expire_in: 2h

.test-c:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_C analyzer/tests/c/$C_FILE

.test-u:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_U analyzer/tests/universal/$U_FILE

.test-py:
  allow_failure: true
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_PY analyzer/tests/python/$PY_FILE

.test-pyty:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_PYTY analyzer/tests/python/types/$PY_FILE

.bench-typpete:
  stage: benchmarks
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - $MOPSA_PYTY benchmarks/pytypes/typpete/$PY_FILE

test-c 1/12:
  variables:
    C_FILE: 'array_tests.c'
  extends: .test-c

test-c 2/12:
  variables:
    C_FILE: 'enum_tests.c'
  extends: .test-c

test-c 3/12:
  variables:
    C_FILE: 'for_tests.c'
  extends: .test-c

test-c 4/12:
  variables:
    C_FILE: 'function_tests.c'
  extends: .test-c

test-c 5/12:
  variables:
    C_FILE: 'goto_tests.c'
  extends: .test-c

test-c 6/12:
  variables:
    C_FILE: 'int_tests.c'
  extends: .test-c

test-c 7/12:
  variables:
    C_FILE: 'malloc_tests.c'
  extends: .test-c

test-c 8/12:
  variables:
    C_FILE: 'pointer_tests.c'
  extends: .test-c

test-c 9/12:
  variables:
    C_FILE: 'string_tests.c'
  extends: .test-c

test-c 10/12:
  variables:
    C_FILE: 'struct_tests.c'
  extends: .test-c

test-c 11/12:
  variables:
    C_FILE: 'switch_tests.c'
  extends: .test-c

test-c 12/12:
  variables:
    C_FILE: 'union_tests.c'
  extends: .test-c

test-u 1/1:
  variables:
    U_FILE: 'int_tests.u'
  extends: .test-u


test-py 1/15:
  variables:
    PY_FILE: 'bool_tests.py'
  extends: .test-py

test-py 2/15:
  variables:
    PY_FILE: 'builtins_tests.py'
  extends: .test-py

test-py 3/15:
  variables:
    PY_FILE: 'class_tests.py'
  extends: .test-py

test-py 4/15:
  variables:
    PY_FILE: 'dict_tests.py'
  extends: .test-py

test-py 5/15:
  variables:
    PY_FILE: 'exception_tests.py'
  extends: .test-py

test-py 6/15:
  variables:
    PY_FILE: 'float_tests.py'
  extends: .test-py

test-py 7/15:
  variables:
    PY_FILE: 'function_tests.py'
  extends: .test-py

test-py 8/15:
  variables:
    PY_FILE: 'generator_tests.py'
  extends: .test-py

test-py 9/15:
  variables:
    PY_FILE: 'int_tests.py'
  extends: .test-py

test-py 10/15:
  variables:
    PY_FILE: 'iter_assign_tests.py'
  extends: .test-py

test-py 11/15:
  variables:
    PY_FILE: 'list_tests.py'
  extends: .test-py

test-py 12/15:
  variables:
    PY_FILE: 'loop_tests.py'
  extends: .test-py

test-py 13/15:
  variables:
    PY_FILE: 'operator_tests.py'
  extends: .test-py

test-py 14/15:
  variables:
    PY_FILE: 'str_tests.py'
  extends: .test-py

test-py 15/15:
  variables:
    PY_FILE: 'with_tests.py'
  extends: .test-py

test-pyty 1/2:
  variables:
    PY_FILE: 'int_tests.py'
  extends: .test-pyty

test-pyty 2/2:
  variables:
    PY_FILE: 'misc_tests.py'
  extends: .test-pyty

bench-typpete 1/38:
  variables:
    PY_FILE: 'builtins_test.py'
  extends: .bench-typpete

bench-typpete 2/38:
  variables:
    PY_FILE: 'callable_class.py'
  extends: .bench-typpete

bench-typpete 3/38:
  variables:
    PY_FILE: 'classes.py'
  extends: .bench-typpete

bench-typpete 4/38:
  variables:
    PY_FILE: 'class_pre_store.py'
  extends: .bench-typpete

bench-typpete 5/38:
  variables:
    PY_FILE: 'comparison_test.py'
  extends: .bench-typpete

bench-typpete 6/38:
  variables:
    PY_FILE: 'cookie.py'
  extends: .bench-typpete

bench-typpete 7/38:
  variables:
    PY_FILE: 'coop_concatenate.py'
  extends: .bench-typpete

bench-typpete 8/38:
  variables:
    PY_FILE: 'crafting_challenge.py'
  extends: .bench-typpete

bench-typpete 9/38:
  variables:
    PY_FILE: 'deceitful.py'
  extends: .bench-typpete

bench-typpete 10/38:
  variables:
    PY_FILE: 'default_args_class.py'
  extends: .bench-typpete

bench-typpete 11/38:
  variables:
    PY_FILE: 'dict_methods.py'
  extends: .bench-typpete

bench-typpete 12/38:
  variables:
    PY_FILE: 'disjoint_sets_nonrec.py'
  extends: .bench-typpete

bench-typpete 13/38:
  variables:
    PY_FILE: 'except_clause.py'
  extends: .bench-typpete

bench-typpete 14/38:
  variables:
    PY_FILE: 'expressions1.py'
  extends: .bench-typpete

bench-typpete 15/38:
  variables:
    PY_FILE: 'expressions.py'
  extends: .bench-typpete

bench-typpete 16/38:
  variables:
    PY_FILE: 'factorization.py'
  extends: .bench-typpete

bench-typpete 17/38:
  variables:
    PY_FILE: 'file_download.py'
  extends: .bench-typpete

bench-typpete 18/38:
  variables:
    PY_FILE: 'functions.py'
  extends: .bench-typpete

bench-typpete 19/38:
  variables:
    PY_FILE: 'generic_class_test.py'
  extends: .bench-typpete

bench-typpete 20/38:
  variables:
    PY_FILE: 'guess_the_number.py'
  extends: .bench-typpete

bench-typpete 21/38:
  variables:
    PY_FILE: 'inheritance_cov_incorrect.py'
  extends: .bench-typpete

bench-typpete 22/38:
  variables:
    PY_FILE: 'inheritance_cov_sat.py'
  extends: .bench-typpete

bench-typpete 23/38:
  variables:
    PY_FILE: 'isinstance.py'
  extends: .bench-typpete

bench-typpete 24/38:
  variables:
    PY_FILE: 'linear_equality.py'
  extends: .bench-typpete

bench-typpete 25/38:
  variables:
    PY_FILE: 'list_methods.py'
  extends: .bench-typpete

bench-typpete 26/38:
  variables:
    PY_FILE: 'magic.py'
  extends: .bench-typpete

bench-typpete 27/38:
  variables:
    PY_FILE: 'math_test.py'
  extends: .bench-typpete

bench-typpete 28/38:
  variables:
    PY_FILE: 'mro.py'
  extends: .bench-typpete

bench-typpete 29/38:
  variables:
    PY_FILE: 'mult_inheritance.py'
  extends: .bench-typpete

bench-typpete 30/38:
  variables:
    PY_FILE: 'override_default_args_correct.py'
  extends: .bench-typpete

bench-typpete 31/38:
  variables:
    PY_FILE: 'prog_1.py'
  extends: .bench-typpete

bench-typpete 32/38:
  variables:
    PY_FILE: 'prog_2.py'
  extends: .bench-typpete

bench-typpete 33/38:
  variables:
    PY_FILE: 'statements.py'
  extends: .bench-typpete

bench-typpete 34/38:
  variables:
    PY_FILE: 'staticmethod.py'
  extends: .bench-typpete

bench-typpete 35/38:
  variables:
    PY_FILE: 'str_methods.py'
  extends: .bench-typpete

bench-typpete 36/38:
  variables:
    PY_FILE: 'stubs_default_args.py'
  extends: .bench-typpete

bench-typpete 37/38:
  variables:
    PY_FILE: 'syntax.py'
  extends: .bench-typpete

bench-typpete 38/38:
  variables:
    PY_FILE: 'unary_test_not.py'
  extends: .bench-typpete

