variables:
  MOPSA_C: "./bin/mopsa-c -unittest"
  MOPSA_U: "./bin/mopsa-universal -unittest"
  MOPSA_PY: "./bin/mopsa-python -unittest"
  MOPSA_PYTY: "./bin/mopsa-python-types -unittest -debug=unittest"
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

image: mopsa-build

stages:
- build
- test
- benchmarks

build_job:
  stage: build
  script:
    - eval `opam config env`
    - make -j
  artifacts:
    paths:
    - ./bin/mopsa
    - ./analyzer/_build/mopsa.native
    expire_in: 2h

.test-c:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - echo $C_FILE
    - $MOPSA_C analyzer/tests/c/$C_FILE

.test-u:
  stage: test
  allow_failure: true
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - echo $U_FILE
    - $MOPSA_U analyzer/tests/universal/$U_FILE

.test-py:
  allow_failure: true
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - echo $PY_FILE
    - $MOPSA_PY analyzer/tests/python/$PY_FILE

.test-pyty:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - echo $PY_FILE
    - $MOPSA_PYTY analyzer/tests/python/types/$PY_FILE

.bench-typpete:
  stage: benchmarks
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - echo $PY_FILE
    - $MOPSA_PYTY benchmarks/pytypes/typpete/$PY_FILE

test-c 1/20:
  variables:
    C_FILE: 'array_tests.c'
  extends: .test-c

test-c 2/20:
  variables:
    C_FILE: 'enum_tests.c'
  extends: .test-c

test-c 3/20:
  variables:
    C_FILE: 'for_tests.c'
  extends: .test-c

test-c 4/20:
  variables:
    C_FILE: 'function_tests.c'
  extends: .test-c

test-c 5/20:
  variables:
    C_FILE: 'goto_tests.c'
  extends: .test-c

test-c 6/20:
  variables:
    C_FILE: 'int_tests.c'
  extends: .test-c

test-c 7/20:
  variables:
    C_FILE: 'stubs/assigns_tests.c'
  extends: .test-c

test-c 8/20:
  variables:
    C_FILE: 'pointer_tests.c'
  extends: .test-c

test-c 9/20:
  variables:
    C_FILE: 'string_tests.c'
  extends: .test-c

test-c 10/20:
  variables:
    C_FILE: 'struct_tests.c'
  extends: .test-c

test-c 11/20:
  variables:
    C_FILE: 'switch_tests.c'
  extends: .test-c

test-c 12/20:
  variables:
    C_FILE: 'union_tests.c'
  extends: .test-c

test-c 13/20:
  variables:
    C_FILE: 'stubs/forall_tests.c'
  extends: .test-c

test-c 14/20:
  variables:
    C_FILE: 'stubs/memory_resource_tests.c'
  extends: .test-c

test-c 15/20:
  variables:
    C_FILE: 'stubs/file_resource_tests.c'
  extends: .test-c

test-c 16/20:
  variables:
    C_FILE: 'stubs/case_tests.c'
  extends: .test-c

test-c 17/20:
  variables:
    C_FILE: 'stubs/macro_tests.c'
  extends: .test-c

test-c 18/20:
  variables:
    C_FILE: 'stubs/var_init_tests.c'
  extends: .test-c

test-c 19/20:
  variables:
    C_FILE: 'stubs/builtins_tests.c'
  extends: .test-c

test-c 20/20:
  variables:
    C_FILE: 'stubs/global_predicate_tests.c'
  extends: .test-c

test-u 1/1:
  variables:
    U_FILE: 'int_tests.u'
  extends: .test-u

test-pyty 1/3:
  variables:
    PY_FILE: 'int_tests.py'
  extends: .test-pyty

test-pyty 2/3:
  variables:
    PY_FILE: 'misc_tests.py'
  extends: .test-pyty

test-pyty 3/3:
  variables:
    PY_FILE: 'exception_tests.py'
  extends: .test-pyty

bench-typpete 1/30:
  variables:
    PY_FILE: 'callable_class.py'
  extends: .bench-typpete

bench-typpete 2/30:
  variables:
    PY_FILE: 'callable_interface_generic.py'
  extends: .bench-typpete

bench-typpete 3/30:
  variables:
    PY_FILE: 'classes.py'
  extends: .bench-typpete

bench-typpete 4/30:
  variables:
    PY_FILE: 'class_pre_store.py'
  extends: .bench-typpete

bench-typpete 5/30:
  variables:
    PY_FILE: 'cookie.py'
  extends: .bench-typpete

bench-typpete 6/30:
  variables:
    PY_FILE: 'coop_concatenate.py'
  extends: .bench-typpete

bench-typpete 7/30:
  variables:
    PY_FILE: 'deceitful.py'
  extends: .bench-typpete

bench-typpete 8/30:
  variables:
    PY_FILE: 'default_args_class.py'
  extends: .bench-typpete

bench-typpete 9/30:
  variables:
    PY_FILE: 'disjoint_sets_nonrec.py'
  extends: .bench-typpete

bench-typpete 10/30:
  variables:
    PY_FILE: 'eight_queens.py'
  extends: .bench-typpete

bench-typpete 11/30:
  variables:
    PY_FILE: 'except_clause.py'
  extends: .bench-typpete

bench-typpete 12/30:
  variables:
    PY_FILE: 'explicit_object_superclass.py'
  extends: .bench-typpete

bench-typpete 13/30:
  variables:
    PY_FILE: 'file_download.py'
  extends: .bench-typpete

bench-typpete 14/30:
  variables:
    PY_FILE: 'guess_the_number.py'
  extends: .bench-typpete

bench-typpete 15/30:
  variables:
    PY_FILE: 'inheritance_cov_incorrect.py'
  extends: .bench-typpete

bench-typpete 16/30:
  variables:
    PY_FILE: 'inheritance_cov_sat.py'
  extends: .bench-typpete

bench-typpete 17/30:
  variables:
    PY_FILE: 'isinstance.py'
  extends: .bench-typpete

bench-typpete 18/30:
  variables:
    PY_FILE: 'linear_equality.py'
  extends: .bench-typpete

bench-typpete 19/30:
  variables:
    PY_FILE: 'list_methods.py'
  extends: .bench-typpete

bench-typpete 20/30:
  variables:
    PY_FILE: 'magic.py'
  extends: .bench-typpete

bench-typpete 21/30:
  variables:
    PY_FILE: 'math_test.py'
  extends: .bench-typpete

bench-typpete 22/30:
  variables:
    PY_FILE: 'mro.py'
  extends: .bench-typpete

bench-typpete 23/30:
  variables:
    PY_FILE: 'mult_inheritance.py'
  extends: .bench-typpete

bench-typpete 24/30:
  variables:
    PY_FILE: 'override_default_args_correct.py'
  extends: .bench-typpete

bench-typpete 25/30:
  variables:
    PY_FILE: 'statements.py'
  extends: .bench-typpete

bench-typpete 26/30:
  variables:
    PY_FILE: 'staticmethod.py'
  extends: .bench-typpete

bench-typpete 27/30:
  variables:
    PY_FILE: 'str_methods.py'
  extends: .bench-typpete

bench-typpete 28/30:
  variables:
    PY_FILE: 'stubs_default_args.py'
  extends: .bench-typpete

bench-typpete 29/30:
  variables:
    PY_FILE: 'syntax.py'
  extends: .bench-typpete

bench-typpete 30/30:
  variables:
    PY_FILE: 'unary_test_not.py'
  extends: .bench-typpete

