from typing import Optional, AnyStr, IO, Any

def NamedTemporaryFile(
    mode: str = ..., buffering: int = ..., encoding: Optional[str] = ...,
    newline: Optional[str] = ..., suffix: Optional[AnyStr] = ..., prefix: Optional[AnyStr] = ...,
    dir: Optional[AnyStr] = ..., delete: bool = ...
) -> IO[AnyStr]: # was IO[Any]...
    ...
