# import typing

# def match(a: typing.Sequence[typing.TypeVar('T', int, float)]) -> typing.TypeVar('T', int, float): ...
# def cons(a: typing.TypeVar('T', int, float)) -> typing.Sequence[typing.TypeVar('T', int, float)]: ...
from typing import Any

def f() -> Any: ...
