TARGET_LIBS = mlUniversalParser

# Packs
mlUniversalParser = U_ast U_ast_printer U_parser U_lexer U_file_parser


# MOPSA
MOPSAROOT = ../..
MOPSALIBS := utils:utils


include $(MOPSAROOT)/make/main.mk
