TARGET_LIBS = mlUniversalParser

MOPSAROOT = ../..

# Packs
mlUniversalParser = U_ast U_ast_printer U_parser U_lexer U_file_parser

# Flags
INCLUDES	:= -I $(MOPSAROOT)/utils/lib

LIBS := utils


include $(MOPSAROOT)/make/main.mk
