TARGET_LIBS = mlCStubsParser

# Packs
mlCStubsParser = c_stubs_parser
c_stubs_parser = ast parser lexer printer scope

# Packages
PKGS = zarith

# MOPSA
MOPSAROOT = ../..
MOPSALIBS := utils:utils parsers/c:mlClangParser


include $(MOPSAROOT)/make/main.mk
