TARGET_LIBS = mlPythonParser

# Packs
mlPythonParser = py_parser
py_parser = cst parser lexer builtins ast pp cst_to_ast scoping main

# Packages
PKGS = zarith

# MOPSA
MOPSAROOT = ../..
MOPSALIBS := utils:utils


include $(MOPSAROOT)/make/main.mk
