TARGET_LIBS = mlPythonParser

# Packs
mlPythonParser = Py_tokens Py_CST Py_parser Py_lexer Py_builtins Py_AST Py_pp Py_CST_to_AST Py_UID

# Packages
PKGS = zarith

# MOPSA
MOPSAROOT = ../..
MOPSALIBS := utils:utils


include $(MOPSAROOT)/make/main.mk
