TARGET_LIBS = mlCAnnotationParser

# Packs
mlCAnnotationParser = c_annot
c_annot = ast parser lexer printer

# Packages
PKGS = zarith

# MOPSA
MOPSAROOT = ../../..
MOPSALIBS := utils:utils


include $(MOPSAROOT)/make/main.mk
