TARGET_CLIBS = utils
MOPSAROOT = ..

utils = bot compare debug dnf equiv setExt setExtSig setP invRelation invRelationSig listExt mapExt mapHet mapPolyHet mapP option printers relation relationSig sig timing top intervals congruences bitfields
intervals = float intBound floatItv intItv

#C files
C_SRC = intervals/floats_x86_64.c

#External packages, as given to ocamlfind
PKGS = str gmp zarith camlidl

include $(MOPSAROOT)/make/main.mk
