TARGET_CLIBS = utils

utils = bot compare debug dnf equiv setExt setExtSig setP invRelation invRelationSig listExt mapExtSig mapExt mapPolyHet mapP optionExt location printers exceptions relation relationSig valueSig timing top itvUtils congUtils bitfields graphSig graph
itvUtils = float intBound intItv floatItv floatItvNan

# C files
C_SRC = itvUtils/floats_x86_64.c

# External packages, as given to ocamlfind
PKGS = str gmp zarith camlidl


MOPSAROOT = ..

include $(MOPSAROOT)/make/main.mk
