TARGET_LIBS = mlStubsParser

# Packs
mlStubsParser = stubs
stubs = c
stubs.c = ast parser lexer printer

# Packages
PKGS = zarith

# MOPSA
MOPSAROOT = ../..
MOPSALIBS := utils:utils parsers/c:mlClangParser


include $(MOPSAROOT)/make/main.mk
